"""add new notif in settings

Revision ID: 97f1ebcda5bf
Revises: 319879973c9b
Create Date: 2025-03-29 15:56:37.515990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f1ebcda5bf'
down_revision: Union[str, None] = '319879973c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('deadline_notif', sa.Boolean(), server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'deadline_notif')
    # ### end Alembic commands ###
